name: simple_scan_linux
description: Dart scanner library
version: 0.1.0
repository: https://github.com/ubuntu-flutter-community/simple_scan.dart

platforms:
  linux:

environment:
  sdk: ^3.5.0

dependencies:
  libsane: ^0.1.0
  simple_scan_platform_interface: ^0.1.0
