name: simple_scan_platform_interface
description: A common platform interface for the simple_scan plugin
version: 0.1.0
repository: https://github.com/ubuntu-flutter-community/sane.dart

environment:
  sdk: ^3.5.0
