// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint

const String NAME_NUM_OPTIONS = '';

const String NAME_STANDARD = 'standard';

const String NAME_GEOMETRY = 'geometry';

const String NAME_ENHANCEMENT = 'enhancement';

const String NAME_ADVANCED = 'advanced';

const String NAME_SENSORS = 'sensors';

const String NAME_PREVIEW = 'preview';

const String NAME_GRAY_PREVIEW = 'preview-in-gray';

const String NAME_BIT_DEPTH = 'depth';

const String NAME_SCAN_MODE = 'mode';

const String NAME_SCAN_SPEED = 'speed';

const String NAME_SCAN_SOURCE = 'source';

const String NAME_BACKTRACK = 'backtrack';

const String NAME_SCAN_TL_X = 'tl-x';

const String NAME_SCAN_TL_Y = 'tl-y';

const String NAME_SCAN_BR_X = 'br-x';

const String NAME_SCAN_BR_Y = 'br-y';

const String NAME_SCAN_RESOLUTION = 'resolution';

const String NAME_SCAN_X_RESOLUTION = 'x-resolution';

const String NAME_SCAN_Y_RESOLUTION = 'y-resolution';

const String NAME_PAGE_WIDTH = 'page-width';

const String NAME_PAGE_HEIGHT = 'page-height';

const String NAME_CUSTOM_GAMMA = 'custom-gamma';

const String NAME_GAMMA_VECTOR = 'gamma-table';

const String NAME_GAMMA_VECTOR_R = 'red-gamma-table';

const String NAME_GAMMA_VECTOR_G = 'green-gamma-table';

const String NAME_GAMMA_VECTOR_B = 'blue-gamma-table';

const String NAME_BRIGHTNESS = 'brightness';

const String NAME_CONTRAST = 'contrast';

const String NAME_GRAIN_SIZE = 'grain';

const String NAME_HALFTONE = 'halftoning';

const String NAME_BLACK_LEVEL = 'black-level';

const String NAME_WHITE_LEVEL = 'white-level';

const String NAME_WHITE_LEVEL_R = 'white-level-r';

const String NAME_WHITE_LEVEL_G = 'white-level-g';

const String NAME_WHITE_LEVEL_B = 'white-level-b';

const String NAME_SHADOW = 'shadow';

const String NAME_SHADOW_R = 'shadow-r';

const String NAME_SHADOW_G = 'shadow-g';

const String NAME_SHADOW_B = 'shadow-b';

const String NAME_HIGHLIGHT = 'highlight';

const String NAME_HIGHLIGHT_R = 'highlight-r';

const String NAME_HIGHLIGHT_G = 'highlight-g';

const String NAME_HIGHLIGHT_B = 'highlight-b';

const String NAME_HUE = 'hue';

const String NAME_SATURATION = 'saturation';

const String NAME_FILE = 'filename';

const String NAME_HALFTONE_DIMENSION = 'halftone-size';

const String NAME_HALFTONE_PATTERN = 'halftone-pattern';

const String NAME_RESOLUTION_BIND = 'resolution-bind';

const String NAME_NEGATIVE = 'negative';

const String NAME_QUALITY_CAL = 'quality-cal';

const String NAME_DOR = 'double-res';

const String NAME_RGB_BIND = 'rgb-bind';

const String NAME_THRESHOLD = 'threshold';

const String NAME_ANALOG_GAMMA = 'analog-gamma';

const String NAME_ANALOG_GAMMA_R = 'analog-gamma-r';

const String NAME_ANALOG_GAMMA_G = 'analog-gamma-g';

const String NAME_ANALOG_GAMMA_B = 'analog-gamma-b';

const String NAME_ANALOG_GAMMA_BIND = 'analog-gamma-bind';

const String NAME_WARMUP = 'warmup';

const String NAME_CAL_EXPOS_TIME = 'cal-exposure-time';

const String NAME_CAL_EXPOS_TIME_R = 'cal-exposure-time-r';

const String NAME_CAL_EXPOS_TIME_G = 'cal-exposure-time-g';

const String NAME_CAL_EXPOS_TIME_B = 'cal-exposure-time-b';

const String NAME_SCAN_EXPOS_TIME = 'scan-exposure-time';

const String NAME_SCAN_EXPOS_TIME_R = 'scan-exposure-time-r';

const String NAME_SCAN_EXPOS_TIME_G = 'scan-exposure-time-g';

const String NAME_SCAN_EXPOS_TIME_B = 'scan-exposure-time-b';

const String NAME_SELECT_EXPOSURE_TIME = 'select-exposure-time';

const String NAME_CAL_LAMP_DEN = 'cal-lamp-density';

const String NAME_SCAN_LAMP_DEN = 'scan-lamp-density';

const String NAME_SELECT_LAMP_DENSITY = 'select-lamp-density';

const String NAME_LAMP_OFF_AT_EXIT = 'lamp-off-at-exit';

const String NAME_FOCUS = 'focus';

const String NAME_AUTOFOCUS = 'autofocus';

const String NAME_SCAN = 'scan';

const String NAME_EMAIL = 'email';

const String NAME_FAX = 'fax';

const String NAME_COPY = 'copy';

const String NAME_PDF = 'pdf';

const String NAME_CANCEL = 'cancel';

const String NAME_PAGE_LOADED = 'page-loaded';

const String NAME_COVER_OPEN = 'cover-open';

const String TITLE_NUM_OPTIONS = 'Number of options';

const String TITLE_STANDARD = 'Standard';

const String TITLE_GEOMETRY = 'Geometry';

const String TITLE_ENHANCEMENT = 'Enhancement';

const String TITLE_ADVANCED = 'Advanced';

const String TITLE_SENSORS = 'Sensors';

const String TITLE_PREVIEW = 'Preview';

const String TITLE_GRAY_PREVIEW = 'Force monochrome preview';

const String TITLE_BIT_DEPTH = 'Bit depth';

const String TITLE_SCAN_MODE = 'Scan mode';

const String TITLE_SCAN_SPEED = 'Scan speed';

const String TITLE_SCAN_SOURCE = 'Scan source';

const String TITLE_BACKTRACK = 'Force backtracking';

const String TITLE_SCAN_TL_X = 'Top-left x';

const String TITLE_SCAN_TL_Y = 'Top-left y';

const String TITLE_SCAN_BR_X = 'Bottom-right x';

const String TITLE_SCAN_BR_Y = 'Bottom-right y';

const String TITLE_SCAN_RESOLUTION = 'Scan resolution';

const String TITLE_SCAN_X_RESOLUTION = 'X-resolution';

const String TITLE_SCAN_Y_RESOLUTION = 'Y-resolution';

const String TITLE_PAGE_WIDTH = 'Page width';

const String TITLE_PAGE_HEIGHT = 'Page height';

const String TITLE_CUSTOM_GAMMA = 'Use custom gamma table';

const String TITLE_GAMMA_VECTOR = 'Image intensity';

const String TITLE_GAMMA_VECTOR_R = 'Red intensity';

const String TITLE_GAMMA_VECTOR_G = 'Green intensity';

const String TITLE_GAMMA_VECTOR_B = 'Blue intensity';

const String TITLE_BRIGHTNESS = 'Brightness';

const String TITLE_CONTRAST = 'Contrast';

const String TITLE_GRAIN_SIZE = 'Grain size';

const String TITLE_HALFTONE = 'Halftoning';

const String TITLE_BLACK_LEVEL = 'Black level';

const String TITLE_WHITE_LEVEL = 'White level';

const String TITLE_WHITE_LEVEL_R = 'White level for red';

const String TITLE_WHITE_LEVEL_G = 'White level for green';

const String TITLE_WHITE_LEVEL_B = 'White level for blue';

const String TITLE_SHADOW = 'Shadow';

const String TITLE_SHADOW_R = 'Shadow for red';

const String TITLE_SHADOW_G = 'Shadow for green';

const String TITLE_SHADOW_B = 'Shadow for blue';

const String TITLE_HIGHLIGHT = 'Highlight';

const String TITLE_HIGHLIGHT_R = 'Highlight for red';

const String TITLE_HIGHLIGHT_G = 'Highlight for green';

const String TITLE_HIGHLIGHT_B = 'Highlight for blue';

const String TITLE_HUE = 'Hue';

const String TITLE_SATURATION = 'Saturation';

const String TITLE_FILE = 'Filename';

const String TITLE_HALFTONE_DIMENSION = 'Halftone pattern size';

const String TITLE_HALFTONE_PATTERN = 'Halftone pattern';

const String TITLE_RESOLUTION_BIND = 'Bind X and Y resolution';

const String TITLE_NEGATIVE = 'Negative';

const String TITLE_QUALITY_CAL = 'Quality calibration';

const String TITLE_DOR = 'Double Optical Resolution';

const String TITLE_RGB_BIND = 'Bind RGB';

const String TITLE_THRESHOLD = 'Threshold';

const String TITLE_ANALOG_GAMMA = 'Analog gamma correction';

const String TITLE_ANALOG_GAMMA_R = 'Analog gamma red';

const String TITLE_ANALOG_GAMMA_G = 'Analog gamma green';

const String TITLE_ANALOG_GAMMA_B = 'Analog gamma blue';

const String TITLE_ANALOG_GAMMA_BIND = 'Bind analog gamma';

const String TITLE_WARMUP = 'Warmup lamp';

const String TITLE_CAL_EXPOS_TIME = 'Cal. exposure-time';

const String TITLE_CAL_EXPOS_TIME_R = 'Cal. exposure-time for red';

const String TITLE_CAL_EXPOS_TIME_G = 'Cal. exposure-time for green';

const String TITLE_CAL_EXPOS_TIME_B = 'Cal. exposure-time for blue';

const String TITLE_SCAN_EXPOS_TIME = 'Scan exposure-time';

const String TITLE_SCAN_EXPOS_TIME_R = 'Scan exposure-time for red';

const String TITLE_SCAN_EXPOS_TIME_G = 'Scan exposure-time for green';

const String TITLE_SCAN_EXPOS_TIME_B = 'Scan exposure-time for blue';

const String TITLE_SELECT_EXPOSURE_TIME = 'Set exposure-time';

const String TITLE_CAL_LAMP_DEN = 'Cal. lamp density';

const String TITLE_SCAN_LAMP_DEN = 'Scan lamp density';

const String TITLE_SELECT_LAMP_DENSITY = 'Set lamp density';

const String TITLE_LAMP_OFF_AT_EXIT = 'Lamp off at exit';

const String TITLE_FOCUS = 'Focus position';

const String TITLE_AUTOFOCUS = 'Autofocus';

const String TITLE_SCAN = 'Scan button';

const String TITLE_EMAIL = 'Email button';

const String TITLE_FAX = 'Fax button';

const String TITLE_COPY = 'Copy button';

const String TITLE_PDF = 'PDF button';

const String TITLE_CANCEL = 'Cancel button';

const String TITLE_PAGE_LOADED = 'Page loaded';

const String TITLE_COVER_OPEN = 'Cover open';

const String DESC_NUM_OPTIONS =
    'Read-only option that specifies how many options a specific device supports.';

const String DESC_STANDARD = 'Source, mode and resolution options';

const String DESC_GEOMETRY = 'Scan area and media size options';

const String DESC_ENHANCEMENT = 'Image modification options';

const String DESC_ADVANCED = 'Hardware specific options';

const String DESC_SENSORS = 'Scanner sensors and buttons';

const String DESC_PREVIEW = 'Request a preview-quality scan.';

const String DESC_GRAY_PREVIEW =
    'Request that all previews are done in monochrome mode.  On a three-pass scanner this cuts down the number of passes to one and on a one-pass scanner, it reduces the memory requirements and scan-time of the preview.';

const String DESC_BIT_DEPTH =
    'Number of bits per sample, typical values are 1 for "line-art" and 8 for multibit scans.';

const String DESC_SCAN_MODE =
    'Selects the scan mode (e.g., lineart, monochrome, or color).';

const String DESC_SCAN_SPEED =
    'Determines the speed at which the scan proceeds.';

const String DESC_SCAN_SOURCE =
    'Selects the scan source (such as a document-feeder).';

const String DESC_BACKTRACK = 'Controls whether backtracking is forced.';

const String DESC_SCAN_TL_X = 'Top-left x position of scan area.';

const String DESC_SCAN_TL_Y = 'Top-left y position of scan area.';

const String DESC_SCAN_BR_X = 'Bottom-right x position of scan area.';

const String DESC_SCAN_BR_Y = 'Bottom-right y position of scan area.';

const String DESC_SCAN_RESOLUTION = 'Sets the resolution of the scanned image.';

const String DESC_SCAN_X_RESOLUTION =
    'Sets the horizontal resolution of the scanned image.';

const String DESC_SCAN_Y_RESOLUTION =
    'Sets the vertical resolution of the scanned image.';

const String DESC_PAGE_WIDTH =
    'Specifies the width of the media.  Required for automatic centering of sheet-fed scans.';

const String DESC_PAGE_HEIGHT = 'Specifies the height of the media.';

const String DESC_CUSTOM_GAMMA =
    'Determines whether a builtin or a custom gamma-table should be used.';

const String DESC_GAMMA_VECTOR =
    'Gamma-correction table.  In color mode this option equally affects the red, green, and blue channels simultaneously (i.e., it is an intensity gamma table).';

const String DESC_GAMMA_VECTOR_R = 'Gamma-correction table for the red band.';

const String DESC_GAMMA_VECTOR_G = 'Gamma-correction table for the green band.';

const String DESC_GAMMA_VECTOR_B = 'Gamma-correction table for the blue band.';

const String DESC_BRIGHTNESS = 'Controls the brightness of the acquired image.';

const String DESC_CONTRAST = 'Controls the contrast of the acquired image.';

const String DESC_GRAIN_SIZE =
    'Selects the "graininess" of the acquired image.  Smaller values result in sharper images.';

const String DESC_HALFTONE =
    'Selects whether the acquired image should be halftoned (dithered).';

const String DESC_BLACK_LEVEL =
    'Selects what radiance level should be considered "black".';

const String DESC_WHITE_LEVEL =
    'Selects what radiance level should be considered "white".';

const String DESC_WHITE_LEVEL_R =
    'Selects what red radiance level should be considered "white".';

const String DESC_WHITE_LEVEL_G =
    'Selects what green radiance level should be considered "white".';

const String DESC_WHITE_LEVEL_B =
    'Selects what blue radiance level should be considered "white".';

const String DESC_SHADOW =
    'Selects what radiance level should be considered "black".';

const String DESC_SHADOW_R =
    'Selects what red radiance level should be considered "black".';

const String DESC_SHADOW_G =
    'Selects what green radiance level should be considered "black".';

const String DESC_SHADOW_B =
    'Selects what blue radiance level should be considered "black".';

const String DESC_HIGHLIGHT =
    'Selects what radiance level should be considered "white".';

const String DESC_HIGHLIGHT_R =
    'Selects what red radiance level should be considered "full red".';

const String DESC_HIGHLIGHT_G =
    'Selects what green radiance level should be considered "full green".';

const String DESC_HIGHLIGHT_B =
    'Selects what blue radiance level should be considered "full blue".';

const String DESC_HUE =
    'Controls the "hue" (blue-level) of the acquired image.';

const String DESC_SATURATION =
    'The saturation level controls the amount of "blooming" that occurs when acquiring an image with a camera. Larger values cause more blooming.';

const String DESC_FILE = 'The filename of the image to be loaded.';

const String DESC_HALFTONE_DIMENSION =
    'Sets the size of the halftoning (dithering) pattern used when scanning halftoned images.';

const String DESC_HALFTONE_PATTERN =
    'Defines the halftoning (dithering) pattern for scanning halftoned images.';

const String DESC_RESOLUTION_BIND = 'Use same values for X and Y resolution';

const String DESC_NEGATIVE = 'Swap black and white';

const String DESC_QUALITY_CAL = 'Do a quality white-calibration';

const String DESC_DOR = 'Use lens that doubles optical resolution';

const String DESC_RGB_BIND = 'In RGB-mode use same values for each color';

const String DESC_THRESHOLD = 'Select minimum-brightness to get a white point';

const String DESC_ANALOG_GAMMA = 'Analog gamma-correction';

const String DESC_ANALOG_GAMMA_R = 'Analog gamma-correction for red';

const String DESC_ANALOG_GAMMA_G = 'Analog gamma-correction for green';

const String DESC_ANALOG_GAMMA_B = 'Analog gamma-correction for blue';

const String DESC_ANALOG_GAMMA_BIND =
    'In RGB-mode use same values for each color';

const String DESC_WARMUP = 'Warm up lamp before scanning';

const String DESC_CAL_EXPOS_TIME = 'Define exposure-time for calibration';

const String DESC_CAL_EXPOS_TIME_R = 'Define exposure-time for red calibration';

const String DESC_CAL_EXPOS_TIME_G =
    'Define exposure-time for green calibration';

const String DESC_CAL_EXPOS_TIME_B =
    'Define exposure-time for blue calibration';

const String DESC_SCAN_EXPOS_TIME = 'Define exposure-time for scan';

const String DESC_SCAN_EXPOS_TIME_R = 'Define exposure-time for red scan';

const String DESC_SCAN_EXPOS_TIME_G = 'Define exposure-time for green scan';

const String DESC_SCAN_EXPOS_TIME_B = 'Define exposure-time for blue scan';

const String DESC_SELECT_EXPOSURE_TIME = 'Enable selection of exposure-time';

const String DESC_CAL_LAMP_DEN = 'Define lamp density for calibration';

const String DESC_SCAN_LAMP_DEN = 'Define lamp density for scan';

const String DESC_SELECT_LAMP_DENSITY = 'Enable selection of lamp density';

const String DESC_LAMP_OFF_AT_EXIT = 'Turn off lamp when program exits';

const String DESC_FOCUS = 'Focus position for manual focus';

const String DESC_AUTOFOCUS = 'Perform autofocus before scan';

const String DESC_SCAN = 'Scan button';

const String DESC_EMAIL = 'Email button';

const String DESC_FAX = 'Fax button';

const String DESC_COPY = 'Copy button';

const String DESC_PDF = 'PDF button';

const String DESC_CANCEL = 'Cancel button';

const String DESC_PAGE_LOADED = 'Page loaded';

const String DESC_COVER_OPEN = 'Cover open';

const String VALUE_SCAN_MODE_COLOR = 'Color';

const String VALUE_SCAN_MODE_COLOR_LINEART = 'Color Lineart';

const String VALUE_SCAN_MODE_COLOR_HALFTONE = 'Color Halftone';

const String VALUE_SCAN_MODE_GRAY = 'Gray';

const String VALUE_SCAN_MODE_HALFTONE = 'Halftone';

const String VALUE_SCAN_MODE_LINEART = 'Lineart';
