name: simple_scan_example
description: Dart scanner library example app
version: 0.1.0
publish_to: none
repository: https://github.com/ubuntu-flutter-community/sane.dart

platforms:
  linux:

environment:
  sdk: ^3.5.0

dependencies:
  logging: ^1.3.0
  simple_scan:
    path: ../
  simple_scan_linux:
    path: ../../simple_scan_linux
